-- 1. Tabelle für die gecrawlten Webseiten erstellen
CREATE TABLE webpages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL,                       -- Die eindeutige URL der Seite
    title TEXT NOT NULL,                            -- Der Titel der Webseite
    content TEXT NOT NULL,                          -- Der gesamte Textinhalt (für die Suche)
    description TEXT,                               -- Eine kurze Beschreibung / Snippet
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Eine spezielle Spalte für die blitzschnelle Volltextsuche hinzufügen (Search Index)
-- Diese Spalte generiert sich automatisch aus Titel, Beschreibung und Inhalt
ALTER TABLE webpages 
ADD COLUMN fts_document tsvector 
GENERATED ALWAYS AS (
    setweight(to_tsvector('german', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('german', coalesce(description, '')), 'B') ||
    setweight(to_tsvector('german', coalesce(content, '')), 'C')
) STORED;

-- Einen Index erstellen, damit Suchen in Millisekunden ausgeführt werden
CREATE INDEX webpages_fts_idx ON webpages USING gin(fts_document);

-- 3. Row Level Security (RLS) aktivieren für die Sicherheit
ALTER TABLE webpages ENABLE ROW LEVEL SECURITY;

-- Eine Sicherheitsregel erstellen: JEDER darf die Webseiten suchen (SELECT)
CREATE POLICY "Jeder darf Webseiten suchen" 
ON webpages 
FOR SELECT 
USING (true);

-- Nur du (mit dem geheimen Service-Rolle-Schlüssel des Crawlers) darfst Daten einfügen (INSERT)
CREATE POLICY "Nur der Crawler darf Daten einfügen" 
ON webpages 
FOR INSERT 
TO service_role 
WITH CHECK (true);